# Generated by Django 2.2 on 2020-12-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201227_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
